[versions]
agp = "8.10.0"
androidx-activityCompose = "1.10.1"
composeBom = "2025.05.00"
coroutines = "1.10.2"
dokkatoo = "2.4.0"
healthConnectClient = "1.1.0-rc01"
java = "21"
kermit = "2.0.5"
kotlin = "2.1.20"
kotlin-dateTime = "0.6.2"
mavenPublish = "0.31.0"
minSdk = "28"
mokkery = "2.7.2"
targetSdk = "35"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
healthConnectClient = { module = "androidx.health.connect:connect-client", version.ref = "healthConnectClient" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlin-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-dateTime" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokkatoo = { id = "dev.adamko.dokkatoo-html", version.ref = "dokkatoo" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
